Imports System.Data.SqlClient
Public Class CLS_SHOW_USE
    Public Sub ADD_(ByVal GUID_UD As String,
                   ByVal FI As Integer,
                   ByVal FI1 As Integer,
                   ByVal FI2 As Integer,
                   ByVal FI3 As Integer,
                   ByVal FI4 As Integer,
                   ByVal FI5 As Integer,
                   ByVal FI6 As Integer,
                   ByVal FI7 As Integer,
                   ByVal FI8 As Integer,
                   ByVal FI9 As Integer,
                   ByVal FI10 As Integer,
                   ByVal ACC As Integer,
                   ByVal ACC1 As Integer,
                   ByVal ACC2 As Integer,
                   ByVal ACC3 As Integer,
                   ByVal ACC4 As Integer,
                   ByVal ACC5 As Integer,
                   ByVal ACC6 As Integer,
                   ByVal ACC7 As Integer,
                   ByVal ACC8 As Integer,
                   ByVal ACC9 As Integer,
                   ByVal ACC10 As Integer,
                   ByVal ACC11 As Integer,
                   ByVal ACC12 As Integer,
                   ByVal MT As Integer,
                   ByVal MT1 As Integer,
                   ByVal MT2 As Integer,
                   ByVal MT3 As Integer,
                   ByVal MT4 As Integer,
                   ByVal MT5 As Integer,
                   ByVal MT6 As Integer,
                   ByVal MT7 As Integer,
                   ByVal MT8 As Integer,
                   ByVal MT9 As Integer,
                   ByVal MT10 As Integer,
                   ByVal INV As Integer,
                    ByVal INV1 As Integer,
                     ByVal INV2 As Integer,
                     ByVal INV3 As Integer,
                     ByVal INV4 As Integer,
                     ByVal INV5 As Integer,
                     ByVal INV6 As Integer,
                     ByVal INV7 As Integer,
                     ByVal INV8 As Integer,
                     ByVal INV9 As Integer,
                     ByVal INV10 As Integer,
                     ByVal INV11 As Integer,
                     ByVal INV12 As Integer,
                     ByVal INV13 As Integer,
                     ByVal INV14 As Integer,
                     ByVal INV15 As Integer,
                     ByVal EMP As Integer,
                     ByVal EMP1 As Integer,
                     ByVal EMP2 As Integer,
                     ByVal EMP3 As Integer,
                     ByVal EMP4 As Integer,
                     ByVal EMP5 As Integer,
                     ByVal EMP6 As Integer,
                     ByVal EMP7 As Integer,
                     ByVal EMP8 As Integer,
                     ByVal EMP9 As Integer,
                     ByVal EMP10 As Integer,
                     ByVal REP_ACC As Integer,
                     ByVal REP_ACC1 As Integer,
                     ByVal REP_ACC2 As Integer,
                     ByVal REP_ACC3 As Integer,
                     ByVal REP_ACC4 As Integer,
                     ByVal REP_ACC5 As Integer,
                     ByVal REP_ACC6 As Integer,
                     ByVal REP_ACC7 As Integer,
                     ByVal REP_ACC8 As Integer,
                     ByVal REP_ACC9 As Integer,
                     ByVal REP_ACC10 As Integer,
                        ByVal REP_MT As Integer,
                      ByVal REP_MT1 As Integer,
                     ByVal REP_MT2 As Integer,
                     ByVal REP_MT3 As Integer,
                     ByVal REP_MT4 As Integer,
                     ByVal REP_MT5 As Integer,
                     ByVal REP_MT6 As Integer,
                     ByVal REP_MT7 As Integer,
                     ByVal REP_MT8 As Integer,
                     ByVal REP_MT9 As Integer,
                     ByVal REP_MT10 As Integer,
                     ByVal REP_MT11 As Integer,
                     ByVal REP_MT12 As Integer,
                        ByVal SETT As Integer,
                 ByVal SETT1 As Integer,
                     ByVal SETT2 As Integer,
                     ByVal SETT3 As Integer,
                     ByVal SETT4 As Integer,
                     ByVal SETT5 As Integer,
                     ByVal SETT6 As Integer,
                     ByVal SETT7 As Integer)

        Dim CON As New CLS_CON
        CON.EXECUTE_TXT("INSERT INTO SHOW_USE(GUID_UD,FI,FI1,FI2,FI3,FI4,FI5,FI6,FI7,FI8,FI9,FI10,ACC,ACC1,ACC2,ACC3,ACC4,ACC5,ACC6,ACC7,ACC8,ACC9,ACC10,ACC11,ACC12,MT,MT1,MT2,MT3,MT4,MT5,MT6,MT7,MT8,MT9,MT10,INV,INV1,INV2,INV3,INV4,INV5,INV6,INV7,INV8,INV9,INV10,INV11,INV12,INV13,INV14,INV15,EMP,EMP1,EMP2,EMP3,EMP4,EMP5,EMP6,EMP7,EMP8,EMP9,EMP10,REP_ACC,REP_ACC1,REP_ACC2,REP_ACC3,REP_ACC4,REP_ACC5,REP_ACC6,REP_ACC7,REP_ACC8,REP_ACC9,REP_ACC10,REP_MT,REP_MT1,REP_MT2,REP_MT3,REP_MT4,REP_MT5,REP_MT6,REP_MT7,REP_MT8,REP_MT9,REP_MT10,REP_MT11,REP_MT12,SETTT,SETTT1,SETTT2,SETTT3,SETTT4,SETTT5,SETTT6,SETTT7)VALUES('" & GUID_UD & "', " & FI & ", " & FI1 & ", " & FI2 & ", " & FI3 & ", " & FI4 & ", " & FI5 & " , " & FI6 & ", " & FI7 & ", " & FI8 & ", " & FI9 & ", " & FI10 & ", " & ACC & ", " & ACC1 & ", " & ACC2 & ", " & ACC3 & ", " & ACC4 & ", " & ACC5 & ", " & ACC6 & ", " & ACC7 & ", " & ACC8 & ", " & ACC9 & ", " & ACC10 & ", " & ACC11 & "," & ACC12 & "," & MT & "," & MT1 & "," & MT2 & "," & MT3 & "," & MT4 & "," & MT5 & "," & MT6 & "," & MT7 & "," & MT8 & "," & MT9 & "," & MT10 & "," & INV & "," & INV1 & "," & INV2 & "," & INV3 & "," & INV4 & "," & INV5 & "," & INV6 & "," & INV7 & "," & INV8 & "," & INV9 & "," & INV10 & "," & INV11 & "," & INV12 & "," & INV13 & "," & INV14 & "," & INV15 & "," & EMP & "," & EMP1 & "," & EMP2 & "," & EMP3 & "," & EMP4 & "," & EMP5 & "," & EMP6 & "," & EMP7 & "," & EMP8 & "," & EMP9 & "," & EMP10 & "," & REP_ACC & "," & REP_ACC1 & "," & REP_ACC2 & "," & REP_ACC3 & "," & REP_ACC4 & "," & REP_ACC5 & "," & REP_ACC6 & "," & REP_ACC7 & "," & REP_ACC8 & "," & REP_ACC9 & "," & REP_ACC10 & "," & REP_MT & "," & REP_MT1 & "," & REP_MT2 & "," & REP_MT3 & "," & REP_MT4 & "," & REP_MT5 & "," & REP_MT6 & "," & REP_MT7 & "," & REP_MT8 & "," & REP_MT9 & "," & REP_MT10 & "," & REP_MT11 & "," & REP_MT12 & "," & SETT & "," & SETT1 & "," & SETT2 & "," & SETT3 & "," & SETT4 & "," & SETT5 & "," & SETT6 & "," & SETT7 & ")")
    End Sub
    'Public Sub ADD_(ByVal GUID_UD As String,
    '             ByVal FI As Integer,
    '             ByVal FI1 As Integer,
    '             ByVal FI2 As Integer,
    '             ByVal FI3 As Integer,
    '             ByVal FI4 As Integer,
    '             ByVal FI5 As Integer,
    '             ByVal FI6 As Integer,
    '             ByVal FI7 As Integer,
    '             ByVal FI8 As Integer,
    '             ByVal FI9 As Integer,
    '             ByVal FI10 As Integer,
    '             ByVal ACC As Integer,
    '             ByVal ACC1 As Integer,
    '             ByVal ACC2 As Integer,
    '             ByVal ACC3 As Integer,
    '             ByVal ACC4 As Integer,
    '             ByVal ACC5 As Integer,
    '             ByVal ACC6 As Integer,
    '             ByVal ACC7 As Integer,
    '             ByVal ACC8 As Integer,
    '             ByVal ACC9 As Integer,
    '             ByVal ACC10 As Integer,
    '             ByVal ACC11 As Integer,
    '             ByVal ACC12 As Integer,
    '             ByVal MT As Integer,
    '             ByVal MT1 As Integer,
    '             ByVal MT2 As Integer,
    '             ByVal MT3 As Integer,
    '             ByVal MT4 As Integer,
    '             ByVal MT5 As Integer,
    '             ByVal MT6 As Integer,
    '             ByVal MT7 As Integer,
    '             ByVal MT8 As Integer,
    '             ByVal MT9 As Integer,
    '             ByVal MT10 As Integer,
    '             ByVal INV As Integer,
    '             ByVal INV1 As Integer,
    '             ByVal INV2 As Integer,
    '             ByVal INV3 As Integer,
    '             ByVal INV4 As Integer,
    '             ByVal INV5 As Integer,
    '             ByVal INV6 As Integer,
    '             ByVal INV7 As Integer,
    '             ByVal INV8 As Integer,
    '             ByVal INV9 As Integer,
    '             ByVal INV10 As Integer,
    '             ByVal INV11 As Integer,
    '             ByVal INV12 As Integer,
    '             ByVal INV13 As Integer,
    '             ByVal INV14 As Integer,
    '             ByVal INV15 As Integer,
    '             ByVal EMP As Integer,
    '             ByVal EMP1 As Integer,
    '             ByVal EMP2 As Integer,
    '             ByVal EMP3 As Integer,
    '             ByVal EMP4 As Integer,
    '             ByVal EMP5 As Integer,
    '             ByVal EMP6 As Integer,
    '             ByVal EMP7 As Integer,
    '             ByVal EMP8 As Integer,
    '             ByVal EMP9 As Integer,
    '             ByVal EMP10 As Integer,
    '             ByVal REP_ACC As Integer,
    '             ByVal REP_ACC1 As Integer,
    '             ByVal REP_ACC2 As Integer,
    '             ByVal REP_ACC3 As Integer,
    '             ByVal REP_ACC4 As Integer,
    '             ByVal REP_ACC5 As Integer,
    '             ByVal REP_ACC6 As Integer,
    '             ByVal REP_ACC7 As Integer,
    '             ByVal REP_ACC8 As Integer,
    '             ByVal REP_ACC9 As Integer,
    '             ByVal REP_ACC10 As Integer,
    '             ByVal REP_MT As Integer,
    '             ByVal REP_MT1 As Integer,
    '             ByVal REP_MT2 As Integer,
    '             ByVal REP_MT3 As Integer,
    '             ByVal REP_MT4 As Integer,
    '             ByVal REP_MT5 As Integer,
    '             ByVal REP_MT6 As Integer,
    '             ByVal REP_MT7 As Integer,
    '             ByVal REP_MT8 As Integer,
    '             ByVal REP_MT9 As Integer,
    '             ByVal REP_MT10 As Integer,
    '             ByVal REP_MT11 As Integer,
    '             ByVal REP_MT12 As Integer,
    '             ByVal SETT As Integer,
    '             ByVal SETT1 As Integer,
    '             ByVal SETT2 As Integer,
    '             ByVal SETT3 As Integer,
    '             ByVal SETT4 As Integer,
    '             ByVal SETT5 As Integer,
    '             ByVal SETT6 As Integer,
    '             ByVal SETT7 As Integer)

    '    Dim CON As New CLS_CON
    '    CON.EXECUTE_TXT("INSERT INTO SHOW_USE(GUID_UD,FI,FI1,FI2,FI3,FI4,FI5,FI6,FI7,FI8,FI9,FI10,ACC,ACC1,ACC2,ACC3,ACC4,ACC5,ACC6,ACC7,ACC8,ACC9,ACC10,ACC11,ACC12,MT,MT1,MT2,MT3,MT4,MT5,MT6,MT7,MT8,MT9,MT10,INV,INV1,INV2,INV3,INV4,INV5,INV6,INV7,INV8,INV9,INV10,INV11,INV12,INV13,INV14,INV15,EMP,EMP1,EMP2,EMP3,EMP4,EMP5,EMP6,EMP7,EMP8,EMP9,EMP10,REP_ACC,REP_ACC1,REP_ACC2,REP_ACC3,REP_ACC4,REP_ACC5,REP_ACC6,REP_ACC7,REP_ACC8,REP_ACC9,REP_ACC10,REP_MT,REP_MT1,REP_MT2,REP_MT3,REP_MT4,REP_MT5,REP_MT6,REP_MT7,REP_MT8,REP_MT9,REP_MT10,REP_MT11,REP_MT12,SETT,SETT1,SETT2,SETT3,SETT4,SETT5,SETT6,SETT7)VALUES('" & GUID_UD & "', " & FI & ", " & FI1 & ", " & FI2 & ", " & FI3 & ", " & FI4 & ", " & FI5 & " , " & FI6 & ", " & FI7 & ", " & FI8 & ", " & FI9 & ", " & FI10 & ", " & ACC & ", " & ACC1 & ", " & ACC2 & ", " & ACC3 & ", " & ACC4 & ", " & ACC5 & ", " & ACC6 & ", " & ACC7 & ", " & ACC8 & ", " & ACC9 & ", " & ACC10 & ", " & ACC11 & "," & ACC12 & "," & MT & "," & MT1 & "," & MT2 & "," & MT3 & "," & MT4 & "," & MT5 & "," & MT6 & "," & MT7 & "," & MT8 & "," & MT9 & "," & MT10 & "," & INV & "," & INV1 & "," & INV2 & "," & INV3 & "," & INV4 & "," & INV5 & "," & INV6 & "," & INV7 & "," & INV8 & "," & INV9 & "," & INV10 & "," & INV11 & "," & INV12 & "," & INV13 & "," & INV14 & "," & INV15 & "," & EMP & "," & EMP1 & "," & EMP2 & "," & EMP3 & "," & EMP4 & "," & EMP5 & "," & EMP6 & "," & EMP7 & "," & EMP8 & "," & EMP9 & "," & EMP10 & "," & REP_ACC & "," & REP_ACC1 & "," & REP_ACC2 & "," & REP_ACC3 & "," & REP_ACC4 & "," & REP_ACC5 & "," & REP_ACC6 & "," & REP_ACC7 & "," & REP_ACC8 & "," & REP_ACC9 & "," & REP_ACC10 & "," & REP_MT & "," & REP_MT1 & "," & REP_MT2 & "," & REP_MT3 & "," & REP_MT4 & "," & REP_MT5 & "," & REP_MT6 & "," & REP_MT7 & "," & REP_MT8 & "," & REP_MT9 & "," & REP_MT10 & "," & REP_MT11 & "," & REP_MT12 & "," & SETT & "," & SETT1 & "," & SETT2 & "," & SETT3 & "," & SETT4 & "," & SETT5 & "," & SETT6 & "," & SETT7 & ")")
    'End Sub
    Public Function SEARSH_(ByVal guid As String)
        Dim CON As New CLS_CON
        Dim DT As New DataTable
        DT.Clear()
        '                            0   1  2    3   4   5   6   7   8   9    10  11   12  13   14   15    16  17   18   19    20   21    22   23    24 25 26   27 28  29  30  31  32  33   34   35  36   37   38   39   40  41    42   43   44   45    46     47   48    49    50    51  52   53  54    55   56   57   58   59    60  61    62       63        64        65      66       67       68        69      70       71       72        73     74      75      76     77       78      79      80     81       82     83        84       85       86   87   88       89      90    91     92     93
        DT = CON.SELECT_TXT(" SELECT FI,FI1,FI2,FI3,FI4,FI5,FI6,FI7,FI8,FI9,FI10,ACC,ACC1,ACC2,ACC3,ACC4,ACC5,ACC6,ACC7,ACC8,ACC9,ACC10,ACC11,ACC12,MT,MT1,MT2,MT3,MT4,MT5,MT6,MT7,MT8,MT9,MT10,INV,INV1,INV2,INV3,INV4,INV5,INV6,INV7,INV8,INV9,INV10,INV11,INV12,INV13,INV14,INV15,EMP,EMP1,EMP2,EMP3,EMP4,EMP5,EMP6,EMP7,EMP8,EMP9,EMP10,REP_ACC,REP_ACC1,REP_ACC2,REP_ACC3,REP_ACC4,REP_ACC5,REP_ACC6,REP_ACC7,REP_ACC8,REP_ACC9,REP_ACC10,REP_MT,REP_MT1,REP_MT2,REP_MT3,REP_MT4,REP_MT5,REP_MT6,REP_MT7,REP_MT8,REP_MT9,REP_MT10,REP_MT11,REP_MT12,SETTT,SETTT1,SETTT2,SETTT3,SETTT4,SETTT5,SETTT6,SETTT7 FROM SHOW_USE where GUID_UD='" & guid & "'")
        Return DT
    End Function
    Sub delete_(ByVal GUID As String)
        Dim CON As New CLS_CON
        CON.EXECUTE_TXT("delete from SHOW_USE where GUID_UD='" & GUID & "'")
    End Sub
End Class
